### ISSUE TITLE
Clean up API validation

### ISSUE THREAD

**Issue by johnhof** [johnhof/IceBuddy#34]
we should handle duplicate keys gracefully. adding duplicate names to teams model currently throws a 500. This should throw a 400 with a warning message

**Comment by DuaneGarber** [comment]
@johnhof Error messaging was fixed with a prior commit. In fact this is out of date because team name is no longer unique.

If you add a dupe email in account register ...
```
{ error: 'Email in use', status: 400, details: null }
      --> 400 - Email in use
```

**Comment by johnhof** [comment]
thanks for looking into it :+1:
